name: Container Build

inputs:
  region:
    required: true
  ecr-repository-uri:
    required: true
  dockerfile-path:
    required: true
  context:
    required: true
  build-args:
    required: false

runs:
  using: composite
  steps:
    - run: |
        aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ inputs.ecr-repository-uri }}
      shell: bash
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.ecr-repository-uri }}
        tags: latest
    - uses: docker/build-push-action@v5
      with:
        push: true
        file: ${{ inputs.dockerfile-path }}
        tags: ${{ steps.meta.outputs.tags }} 
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
    - run: |
        docker rmi ${{ steps.meta.outputs.tags }} || true
      shell: bash


