name: Setup application env (Kong Gateway)

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

jobs:
  ApplicationBuild:
    name: Application build (Kong Gateway)
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: ./.github/workflows/application-build-kong-gateway.yml
    with:
      GITHUB_ENV: ${{ inputs.target_env }}
  
  DeletePreviousJob:
    name: Delete Previous Job
    needs: ApplicationBuild
    runs-on: ec2-iac-platform-${{ inputs.target_env }}
    environment: ${{ inputs.target_env }}
    steps:
      - uses: ./.github/actions/delete-eks-job
        with:
          job-name: themis2-${{ inputs.target_env }}-kong-setting
          aws-account: ${{ vars.AWS_ACCOUNT }}
          aws-region: ${{ vars.AWS_REGION }}
          backend-bucket-name: themis2-${{ inputs.target_env }}-s3-tfstate
          working-dir: themis2-inf-platform/${{ vars.TOFU_WORK_DIR }}

  Provision:
    name: Kong Gateway Provision
    needs: DeletePreviousJob
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: ./.github/workflows/inf-platform-opentofu-applying-self-hosted.yml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
      module-name: KongSetting
      target: |
        -target=module.ekspod_infra.kubernetes_manifest.kong_setting
      health-check-command: |
        cd themis2-inf-platform/${{ vars.TOFU_WORK_DIR }}
        EKS_CLUSTER_NAME=$(tofu output eks_cluster_name)
        aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME//\"/}
        kubectl wait --for=condition=complete job -l name=kong-setting,app=app --timeout=300s
