name: Setup application env (HPA - Horizontal Pod Autoscaler)

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

jobs:
  Provision-1:
    name: HPA Provision (Servicer1)
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: ./.github/workflows/inf-servicer-opentofu-applying-self-hosted.yml
    secrets: inherit
    with:
      module-name: HorizontalPodAutoscaler
      target: |
        -target=module.ekspod_sol_prov.kubernetes_manifest.sample_analyzer_hpa \
        -target=module.ekspod_sol_prov.kubernetes_manifest.realtime_transform_hpa \
        -target=module.ekspod_sol_prov.kubernetes_manifest.keycloak_hpa \
        -target=module.ekspod_sol_prov.kubernetes_manifest.data_filtering_api_hpa
      target_env: ${{ inputs.target_env }}
      ekspod: sol_prov

  Provision-2:
    name: HPA Provision (Servicer2)
    needs: Provision-1
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: ./.github/workflows/inf-servicer-opentofu-applying-self-hosted.yml
    secrets: inherit
    with:
      module-name: HorizontalPodAutoscaler
      target: |
        -target=module.ekspod_sol_prov2.kubernetes_manifest.sample_analyzer_hpa \
        -target=module.ekspod_sol_prov2.kubernetes_manifest.realtime_transform_hpa \
        -target=module.ekspod_sol_prov2.kubernetes_manifest.keycloak_hpa \
        -target=module.ekspod_sol_prov2.kubernetes_manifest.data_filtering_api_hpa
      target_env: ${{ inputs.target_env }}
      ekspod: sol_prov2
