name: Provision IaC Environment (S3/VPC/EC2)

on:
  workflow_dispatch:
    inputs:
      target_env:
        required: true
        type: string

jobs:
  IaC-Environment:
    name: Provision IaC Environment (S3/VPC/EC2)
    permissions:
      id-token: write
      contents: read
      actions: write
    uses: ./.github/workflows/inf-servicer-setup-iac-env.yml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
